kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-blobs
  namespace: girons
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-data
  namespace: girons
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-snapshots
  namespace: girons
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
