# ---------- Exposer service ------------
apiVersion: v1
kind: Service
metadata:
  name: giropops-service
  namespace: girons
spec:
  selector:
    name: giropops
  clusterIP: None
  ports:
  - name:  xp-port
    port:  8080
    targetPort:  8080